config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 拠点
  resources :offices, only: [:index, :create, :update, :destroy]
  
  resources :users do
    collection { post :import }
    member do
      get 'export_csv_attendance'          # /users/:id/export_csv_attendance          ユーザー一人分の勤怠をcsv出力
      get 'edit_basic_info'                # /users/:id/edit_basic_info　　　　　　　　ユーザーの基本情報編集
      patch 'update_basic_info'            # /users/:id/update_basic_info　　　　　　　
      get 'attendances/edit_one_month'     # /users/:id/attendances/edit_one_month　　　1ヶ月の勤怠をまとめて編集画面
      patch 'attendances/update_one_month' # /users/:id/attendances/update_one_month    1ヶ月の勤怠をまとめて保存
      get 'applies/edit_month'             # /users/:id/applies/edit_month　　　　　   モーダルで1ヶ月分勤怠の申請編集画面
      patch 'applies/update_month'         # /users/:id/applies/update_month　　　　
      get 'attendances/change_one_month'   # /users/:id/attendances/change_one_month　　モーダルで勤怠の変更申請まとめて編集画面
      patch 'attendances/update_change_one_month' # /users/:id/attendances/update_change_one_month　モーダルで勤怠の変更申請まとめて編集画面　　　
      get 'attendances/edit_overtime'   # /users/:id/attendances/edit_overtime　　モーダルで残業申請（申請者側）
      patch 'attendances/update_overtime' # /users/:id/attendances/update_overtime　　　　
      get 'attendances/edit_judgment_overtime'   # /users/:id/attendances/edit_judgment_overtime　　モーダルで残業申請のジャッジを編集（上長側）
      patch 'attendances/update_judgment_overtime' # /users/:id/attendances/update_judgment_overtime
      get 'attendances/log_index'   # /users/:id/attendances/log_index　　　　　　　　　モーダルで残業申請のジャッジを編集（上長側）
      get 'working_employees'       # /users/:id/working_employees　　　　　　　　　　　出勤中社員一覧
      get 'edit_system_info'  # /users/:id/edit_system_info
    end
    resources :attendances, only: :update  # /users/:user_id/attendances/:id 　　　　　出勤登録
    
    resources :applies, only: :update      # /users/:user_id/applies/:id　　　　　　　　最初の1ヶ月の勤怠申請
  end
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :user
  
  attr_accessor :check
  
  validates :month, presence: true

  validate :apply_is_invalid_without_a_authorizer       #所属長承認申請には所属長の選択が必要

  def apply_is_invalid_without_a_authorizer
    errors.add(:authorizer, "が必要です")if authorizer.blank? && mark == 2
  end

end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  
  def update

    @user = User.find(params[:user_id])
    @apply = Apply.find(params[:apply][:id])

    if params[:apply][:authorizer].present?
      if @apply.update_attributes(applies_params)
        flash[:info] = "一か月分の承認申請しました"
      else
        flash[:danger] = "承認申請に失敗しました。やり直してください。"
      end
      
    else
        flash[:danger] = "承認申請に失敗しました。やり直してください。"
    end
    
    redirect_to @user
  end

  def edit_month
    @user = User.find(params[:id])
    @applies = Apply.where(authorizer: @user.id).where(mark: 1)
    apply_id_array = []
    @applies.each do |apply|
      apply_id_array.push(apply.user_id)
    end
    @apply_id_array = apply_id_array.uniq
  end

  # 上長が勤怠の申請を承認・否認したものを保存する機能
  def update_month
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      month_params.each do |id, item|
        apply = Apply.find(id)
        if params[:user][:applies][id][:check] == "1"
          apply.update_attributes!(item)
          flash[:success] = "所属長承認申請を更新しました。"
        end
      end
    end
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to applies_update_month_user_url(date: params[:date])
  end

  
    private

    def applies_params
      params.require(:apply).permit(:month, :mark, :authorizer, :id, :apply_id)
    end
    
    def month_params
      params.require(:user).permit(applies: [:month, :mark, :check, :authorizer, :id, :apply_id])[:applies]
    end
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/views/applies/_edit_month.html.erb
<% provide(:class_text, 'basic-info') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= form_with(model: @user, url: applies_update_month_user_path(), local: true, method: :patch) do |f| %>
            <% @apply_id_array.each do |apply_user_id| %>
              <% user = User.find(apply_user_id) %>
              <h2>【<%= user.name %>からの1ヶ月勤怠申請】</h2>
                <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                  <thead>
                    <tr>
                      <th><%= Apply.human_attribute_name(:month) %></th>
                      <th><%= Apply.human_attribute_name(:mark) %></th>
                      <th>変更</th>
                      <th>勤怠を確認する</th>
                    </tr>
                  </thead>
                <tbody>
                  <% applies = user.applies.where(mark: 1).where(authorizer: current_user.id) %>
                  <% applies.each do |sinsei| %>
                    <%= f.fields_for "applies[]", sinsei do |af| %>
                      <tr>
                        <td><%= sinsei.month.month %></td>
                        <td><%= af.select :mark, [['なし', 0], ['申請中', 1], ['承認', 2], ['否認', 3]], { include_blank: true, selected: sinsei.mark } %></td>
                        <td><%= af.check_box :check %></td>
                        <td><%= link_to "確認する", user_path(sinsei.user_id, date:sinsei.month), class: "btn btn-lg btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            <% end %>
 　　　　       <div class="center">
   　　　        <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/applies/edit_month.js.erb
$("#applies-edit-month").html("<%= escape_javascript(render 'applies/edit_month') %>");
$("#applies-edit-month").modal("show");