config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 拠点
  resources :offices, only: [:index, :create, :update, :destroy]
  
  resources :users do
    collection { post :import }
    member do
      get 'export_csv_attendance'          # /users/:id/export_csv_attendance          ユーザー一人分の勤怠をcsv出力
      get 'edit_basic_info'                # /users/:id/edit_basic_info　　　　　　　　ユーザーの基本情報編集
      patch 'update_basic_info'            # /users/:id/update_basic_info　　　　　　　
      get 'attendances/edit_one_month'     # /users/:id/attendances/edit_one_month　　　1ヶ月の勤怠をまとめて編集画面
      patch 'attendances/update_one_month' # /users/:id/attendances/update_one_month    1ヶ月の勤怠をまとめて保存
      get 'applies/edit_month'             # /users/:id/applies/edit_month　　　　　   モーダルで1ヶ月分勤怠の申請編集画面
      patch 'applies/update_month'         # /users/:id/applies/update_month　　　　
      get 'attendances/change_one_month'   # /users/:id/attendances/change_one_month　　モーダルで勤怠の変更申請まとめて編集画面
      patch 'attendances/update_change_one_month' # /users/:id/attendances/update_change_one_month　モーダルで勤怠の変更申請まとめて編集画面　　　
      get 'attendances/edit_overtime'   # /users/:id/attendances/edit_overtime　　モーダルで残業申請（申請者側）
      patch 'attendances/update_overtime' # /users/:id/attendances/update_overtime　　　　
      get 'attendances/edit_judgment_overtime'   # /users/:id/attendances/edit_judgment_overtime　　モーダルで残業申請のジャッジを編集（上長側）
      patch 'attendances/update_judgment_overtime' # /users/:id/attendances/update_judgment_overtime
      get 'attendances/log_index'   # /users/:id/attendances/log_index　　　　　　　　　モーダルで残業申請のジャッジを編集（上長側）
      get 'working_employees'       # /users/:id/working_employees　　　　　　　　　　　出勤中社員一覧
      get 'edit_system_info'  # /users/:id/edit_system_info
    end
    resources :attendances, only: :update  # /users/:user_id/attendances/:id 　　　　　出勤登録
    
    resources :applies, only: :update      # /users/:user_id/applies/:id　　　　　　　　最初の1ヶ月の勤怠申請
  end
end

app/models/user.rb
class User < ApplicationRecord
  # 一対多の関係を記述, ユーザーが削除された場合関連する勤怠データも自動で削除される設定
  has_many :attendances, dependent: :destroy
  has_many :applies, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost =
    if ActiveModel::SecurePassword.min_cost
      BCrypt::Enggin::MIN_COST
    else
      BCrypt::Engine.cost
    end
  BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #ユーザー名による絞り込み
scope :get_by_name, ->(name) {
where("name like ?", "%#{name}%")
}


  def self.import(file)
    # CSV.foreach(file.path, headers: true) do |row|
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      # user = find_by(id: row["id"]) || new
      user = new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
  end

   # 更新を許可するカラムを定義
   def self.updatable_attributes
     ["id", "name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "admin", "superior", "password", "password_digest"]
   end
end

app/controllers/users_controller.rb
require "csv"

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :export_csv_attendance]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info, :working_employees, :edit_system_info, :import]
  before_action :not_admin_user, only: :show
  before_action :set_one_month, only: [:show, :export_csv_attendance]
  before_action :set_apply_month, only: :show

  def index
    @users = User.paginate(page: params[:page])
    # パラメータとして名前か性別を受け取っている場合は絞って検索する
    if params[:name].present?
      @searches = @users.get_by_name params[:name]
    end
  end

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    # 1ヶ月の勤怠認証の為
    @authorizers= User.where(superior: true ).where.not(id: @user.id)
    @applies = Apply.where(authorizer: @user.id).where(mark: 1)
    # 勤怠変更認証の為
    @change_attendances = Attendance.where(applying_change_authorizer_id: @user.id).where(mark: 1)
    @overtime_attendances = Attendance.where(overtime_authorizer_id: @user.id).where(overtime_mark: 1)
  end

  def new
    @user = User.new
  end
  
  def create
    @user= User.new(user_params)
    @user.designated_work_start_time = "09:00"
    @user.designated_work_end_time = "18:00"
    if @user.save
      log_in @user # 保存成功後、ログインします。
      flash[:success] ='新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      # 更新に成功した場合の処理を記述します
      flash[:success] = 'ユーザー情報を更新しました。'
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def import
    if params[:file].present?
      # fileはtmpに自動で一時保存される
      User.import(params[:file])
      flash[:success] = "CSVファイルインポートに成功しました。"
      redirect_to users_url
    else
      flash[:danger] = "失敗しました。やり直して下さい。"
      redirect_to users_url
    end
  end
  
  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end

  # 管理権限者、または現在ログインしているユーザーを許可します。
  def show_admin_or_correct_user
    # @user = User.find(params[:user_id]) if @user.blank?
    @user = User.find(params[:id]) if @user.blank?
    unless current_user?(@user) || current_user.admin?
      flash[:danger] = "権限がありません。"
      redirect_to(root_url)
    end
  end

  def working_employees
    attendances = Attendance.where.not(started_at: nil).where(finished_at: nil)
    working_employees_ids = []
    attendances.each do |attendance|
      working_employees_ids.push(attendance.user_id)
    end
    @working_employees_ids = working_employees_ids
  end


  def export_csv_attendance
    head :no_content

    # users = User.where(town_id: params[:id]) users => @attendances
    # town = Town.find(params[:id])            town =>  @user
    #ファイル名を指定 ここはお好みで
    # filename = @user.name + Date.current.strftime("%Y%m%d")
    filename = @user.name + "　" +  l(@first_day, format: :middle) + "勤怠"
    #日本語のカラム名を用意
    columns_ja = ["日付", "出勤", "退勤"]
    
    columns = ["worked_on", "started_at", "finished_at"]

    csv1 = CSV.generate do |csv|
      #カラム名を1行目として入れる
      # csv << Attendance.column_names   これだと全てのカラムが出力されてしまう
      # csv_column_names = %w(worked_on started_at finished_at)
      # csv_column_names = %w(worked_on started_at finished_at)
      # csv << csv_column_names   # 表の列に入る名前を定義します。

      csv << columns_ja
      @attendances.each do |attendance|
        #各行の値を入れていく
        # csv << attendance.attributes.values_at(*Attendance.column_names)
        column_values = [
          attendance.worked_on,
          attendance.started_at.try(:strftime,"%H:%M"),
          attendance.finished_at.try(:strftime,"%H:%M")
        ]
        csv << column_values   #表の行に入る値を定義します。
        # csv << attendance.attributes.values_at(*columns)
      end
    end
    create_csv(filename, csv1)
  end

  def edit_system_info
  end

  private

    def create_csv(filename, csv1)
      #ファイル書き込み
      File.open("./#{filename}.csv", "w", encoding: "SJIS") do |file|
        file.write(csv1)
      end
      #send_fileを使ってCSVファイル作成後に自動でダウンロードされるようにする
      stat = File::stat("./#{filename}.csv")
      send_file("./#{filename}.csv", filename: "#{filename}.csv", length: stat.size)
    end

    def user_params
      params.require(:user).permit(:name, :email, :department,:password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time, :name, :email, :affiliation, :employee_number, :uid, :designated_work_start_time, :designated_work_end_time, :basic_work_time, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end 
  
end

app/views/users/_form.html.1.erb
<%= form_with(model: @user, local:true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
               
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local:true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
               
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_user.html.erb
<%= form_with(model: user, url: update_basic_info_user_path(user), local: true) do |f| %>

<% if user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力エラーが<%= user.errors.count %>件ありました。
    </div>
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "アカウント情報の更新") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>

<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報の更新") %>
<% provide(:class_text, "basic-info") %>
<% provide(:button_text, "編集") %>

<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
     
      <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_time, class: "form-control" %>
     
      <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :work_time, class: "form-control" %>
     
     <%= f.submit "#{yield(:button_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    
    <% end %>
  </div>
</div>

app/views/users/edit_system_info.html.erb
<% provide(:title, "") %>
<% provide(:class_text, '') %>
<% provide(:button_text, '') %>
<h1>システム全体の基本情報更新</h1>
<p>現在未実装</p>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集する') %>
<h1>ユーザー一覧</h1>
<div class="row">
	<div class="col-md-11">
	  <div class="col-md-3 mb-50">
		<%= form_tag import_users_path, multipart: true do %>
		  <%= file_field_tag :file %>
		  <%= submit_tag "CSVをインポート", class: "btn btn-primary btn-block"  %>
		<% end %>
  </div>
  </div>
</div>


<div class="row">
  <div class="col-md-10 col-md-offset-1">
	<% @users.each do |user| %>
	    <% if !user.admin %>
	      <div><%= user.name %></div>
		    <div>
		    	｜
		    	<%= link_to "削除", user, method: :delete,
		    	    data: { confirm: "削除してよろしいですか？" },
		    	    class:"btn btn-primary" %>
		    </div>
				<div class="panel-group">
				  <div class="panel panel-default">
				    <div class="panel-heading">
					  <h3 class="panel-title">
					    <a data-toggle="collapse" href="#sampleAccordionCollapse<%= user.id %>">
						  <button class="btn btn-primary btn-lg">編集</button>
						</a>
					  </h3>
					</div>
					<div id="sampleAccordionCollapse<%= user.id %>" class="panel-collapse collapse">
					  <div class="panel-body">
					    <%= render 'user', user: user %>
					  </div>
					</div>
				  </div>
				</div>
	    <% end %>
	    
	<% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'アカウント作成') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '申請する') %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <th>
        <% if current_user == @user %>
          <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        <% end %>
        <span>　</span>
        <%= l(@first_day, format: :middle) %>
        時間管理表
        <span>　</span>
        <% if current_user == @user %>
          <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
        <% end %>
      </th>
      <th>
        <%= User.human_attribute_name(:designated_work_start_time) %>　
        <%= format_basic_info(@user.designated_work_start_time) if @user.designated_work_start_time.present? %>
        <br>
        基本勤務終了時間　
        <% if @user.designated_work_end_time.present? %>
          <%= format_basic_info(@user.designated_work_end_time) %>
        <% end %>
      </th>
      <th colspan='3'>基本時間
        <% if @user.basic_work_time.present? %>
          <%= format_basic_info(@user.basic_work_time) %>
        <% end %> 
      </th>
      <th>初日　<%=l(@first_day, format: :short) %></th>
    </tr>

    <tr>
      <th><%= User.human_attribute_name("affiliation")%>　<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></th>
      <th><%= User.human_attribute_name("name")%>　<%= @user.name %></th>
      <th><%= User.human_attribute_name("employee_number")%></th>
      <th><%= @user.employee_number.present? ? @user.employee_number : "　　" %></th>
      <th>出勤日数　<%= @worked_sum %>日</th>
      <th>締め　<%= l(@last_day, format: :short) %></th>
    </tr>
  </table>
</div>
<% if current_user == @user %>
  <% if current_user.superior %>
    <% if @applies.count > 0 %>
      <P class="danger-color">
        【所属長承認申請のお知らせ】<span class="visible-inline danger-color box-danger"><%= link_to "#{@applies.count}件の申請があります", applies_edit_month_user_path(@user, @applies), remote: true, class: "btn-notice danger-color" %></span>
      </P>
    <% else %>
      <P>【所属長承認申請のお知らせ】</P>
    <% end %>
    <% if @change_attendances.count > 0 %>
      <p class="danger-color">
        【勤怠変更申請のお知らせ】<span class="visible-inline danger-color box-danger"><%= link_to "#{@change_attendances.count}件の申請があります", attendances_change_one_month_user_path(@user), remote: true, class: "btn-notice danger-color" %></span>
      </p>
    <% else %> 
      <p>【勤怠変更申請のお知らせ】</p>
    <% end %>
    
    <% if @overtime_attendances.count > 0 %>
      <p class="danger-color">
        【残業申請のお知らせ】<span class="visible-inline danger-color box-danger"><%= link_to "#{@overtime_attendances.count}件の申請があります", attendances_edit_judgment_overtime_user_path(@user, view_date: @first_day), remote: true, class: "btn-notice danger-color" %></span>
      </p>
    <% else %> 
      <p>【残業申請のお知らせ】</p>
    <% end %>
    
  <% end %>
  <%= link_to "勤怠の編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", export_csv_attendance_user_path(id: @user.id), class: "btn btn-primary" %><br>
  <%= link_to "勤怠修正ログ（承認済）", attendances_log_index_user_path, class: "btn btn-primary mb-20" %>
  <div>
<% end %>
  <table class="table table-bordered table-striped table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">【所定外勤務】</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead> 

    <tbody>
      <% @attendances.each do |day| %>
        <%
          css_class = 
          case $days_of_the_week[day.worked_on.wday]
          when '土'
            'text-primary'
          when '日'
            'text-danger'
          end
        %>
        <tr>
          <th>
            <% if current_user == @user %>
              <%= link_to "残業申請", attendances_edit_overtime_user_path(@user, overtime_attendance: day), remote: true, class: "btn btn-primary" %>
            <% end %>
          </th>
          <th><%= l(day.worked_on, format: :short) %></th>
          <th class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></th>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= format_minute_per_fifteen(day.started_at) if day.started_at.present? %></td>
          <!--<td><%= day.started_at.min if day.started_at.present? %></td>-->
          <td>
            <% if current_user == @user %>
              <% if btn_text = attendance_state(day) %>
                <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
              <% end %>
            <% end %>
          </td>
          <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td> 
          <td><%= format_minute_per_fifteen(day.finished_at) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times =working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= day.overtime_finished_at.hour if day.overtime_finished_at.present? %></td>
          <td><%= day.overtime_finished_at.min if day.overtime_finished_at.present? %></td>
          <!--計算用に日付変更する-->
          <% calc_designated_work_end_time = @user.designated_work_end_time.change(month: day.worked_on.month, day: day.worked_on.day) %>
          <!--残業時間ー終了予定時間で計算-->
          <td><%= sprintf("%.2f", (day.overtime_finished_at - calc_designated_work_end_time) / 60 / 60) if day.overtime_finished_at.present? && @user.designated_work_end_time.present? %></td>
          <td><%= day.overtime_note %></td>
          <td>
            <%= User.find(day.applying_change_authorizer_id).name if day.applying_change_authorizer_id.present? %>
            <%= User.find(day.change_authorizer_id).name if day.change_authorizer_id.present? %><span>　</span><%= $mark_change[day.mark] %>
            <% $mark_change2 = %w{　 残業申請中 残業申請承認済 残業申請否認} %>
            <%= User.find(day.overtime_authorizer_id).name if day.overtime_authorizer_id.present? %><span>　</span><%= $mark_change2[day.overtime_mark] %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr class="active">
        <th></th>
        <th colspan="2"><%=  format("%.2f",format_basic_info(@user.work_time).to_f * @worked_sum) %></th>
        <th colspan="6"></th>
        <th><%= format("%.2f", @total_working_times.to_f) %></th>
        <td colspan="5"></td>
        <th>
          所属長承認 　<% if @apply.authorizer.present? %><%= User.find(@apply.authorizer).name %><% end %><%= $mark_status[@apply.mark] %>

          <% if current_user == @user %>
            <%= form_with(model: @apply, url: user_apply_path(@user), method: :patch, local: true) do |f| %>
              <%= f.collection_select(:authorizer, @authorizers, :id, :name , prompt: "") %>
              <%= f.hidden_field :mark, :value => "1" %>
              <%= f.hidden_field :month, :value => @first_day %>
              <%= f.hidden_field :user_id, :value => @user.id %>
              <%= f.hidden_field :id, :value => @apply.id %>

              <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
            <% end %>
          <% end %>
        </th>
      </tr>
    </tfoot>
  </table>
</div>

<!--1ヶ月申請の承認モーダルウインドウ表示-->
<div id="applies-edit-month" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<!--勤怠変更の承認モーダルウインドウ表示-->
<div id="attendances-change-one-month" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<!--残業申請モーダルウインドウ表示（申請者用）-->
<div id="edit-overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<!--残業申請モーダルウインドウ表示（上長用）-->
<div id="edit_judgment_overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/working_employees.html.erb
<% provide(:title, '出勤中社員一覧') %>

<div class = "mt-50">
    <h1>出勤中社員一覧</h1>
    <% if @working_employees_ids.count > 0 %>
      <table class="table table-bordered table-condensed user-table table-text-center">
        <tr>
          <th><%= User.human_attribute_name(:employee_number) %></th>
          <th><%= User.human_attribute_name(:name) %></th>
        </tr>
          <% @working_employees_ids.each do |id| %>
            <% employee = User.find(id) %>
            <tr>
              <td><%= employee.employee_number %></td>
              <td><%= employee.name %></td>
            </tr>
          <% end %>
      </table>
    <% else %>
      <p>現在、出勤中の社員はいません。</p>
    <% end %>
</div>