config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 拠点
  resources :offices, only: [:index, :create, :update, :destroy]
  
  resources :users do
    collection { post :import }
    member do
      get 'export_csv_attendance'          # /users/:id/export_csv_attendance          ユーザー一人分の勤怠をcsv出力
      get 'edit_basic_info'                # /users/:id/edit_basic_info　　　　　　　　ユーザーの基本情報編集
      patch 'update_basic_info'            # /users/:id/update_basic_info　　　　　　　
      get 'attendances/edit_one_month'     # /users/:id/attendances/edit_one_month　　　1ヶ月の勤怠をまとめて編集画面
      patch 'attendances/update_one_month' # /users/:id/attendances/update_one_month    1ヶ月の勤怠をまとめて保存
      get 'applies/edit_month'             # /users/:id/applies/edit_month　　　　　   モーダルで1ヶ月分勤怠の申請編集画面
      patch 'applies/update_month'         # /users/:id/applies/update_month　　　　
      get 'attendances/change_one_month'   # /users/:id/attendances/change_one_month　　モーダルで勤怠の変更申請まとめて編集画面
      patch 'attendances/update_change_one_month' # /users/:id/attendances/update_change_one_month　モーダルで勤怠の変更申請まとめて編集画面　　　
      get 'attendances/edit_overtime'   # /users/:id/attendances/edit_overtime　　モーダルで残業申請（申請者側）
      patch 'attendances/update_overtime' # /users/:id/attendances/update_overtime　　　　
      get 'attendances/edit_judgment_overtime'   # /users/:id/attendances/edit_judgment_overtime　　モーダルで残業申請のジャッジを編集（上長側）
      patch 'attendances/update_judgment_overtime' # /users/:id/attendances/update_judgment_overtime
      get 'attendances/log_index'   # /users/:id/attendances/log_index　　　　　　　　　モーダルで残業申請のジャッジを編集（上長側）
      get 'working_employees'       # /users/:id/working_employees　　　　　　　　　　　出勤中社員一覧
      get 'edit_system_info'  # /users/:id/edit_system_info
    end
    resources :attendances, only: :update  # /users/:user_id/attendances/:id 　　　　　出勤登録
    
    resources :applies, only: :update      # /users/:user_id/applies/:id　　　　　　　　最初の1ヶ月の勤怠申請
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  attr_accessor :view_date      #モデルに基づかない項目をform_withで送信する場合に記載
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  validates :overtime_instruction, length: { maximum: 50 }
  validates :instructor, length: {maximum: 50 }
  
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at

  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  
  # 追加バリデーション
  # validate :applying_started_at_than_applying_finished_at_if_invalid
  
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です")if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  
  # 追加バリデーション
  # def applying_started_at_than_applying_finished_at_if_invalid
  #   if applying_started_at.present? && applying_finished_at.present? && change_authorizer_id.present?
  #     errors.add(:applying_started_at, "より早い退勤時間は無効です") if applying_started_at > applying_finished_at
  #   end
  # end
  
end
      

app/helpers/attendances_helper.rb
require 'rounding'
module AttendancesHelper
  
  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    # if文は条件式がtrueなら処理を実行し、falseならなにも処理を実行しない。つまりボタンは表示されない。
    if  Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    # Rubyではメソッドの最後の式のreturnを省略できるようだ。
    false
  end
  
  # 出社と退社時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f",(((finish.floor_to(15.minutes) - start.floor_to(15.minutes)) / 60) / 60.0))
  end
  
  # 勤怠時間を受け取り15分単位で切捨てて表示します
  def format_minute_per_fifteen(time)
    # 詳しい使い方はここを参照　https://github.com/brianhempel/rounding/blob/master/README.md
    (time.floor_to(15.minutes)).min
  end  
end

app/views/attendances/_change_one_month.html.erb
<!--勤怠変更を承認する上長側モーダル表示-->
<% provide(:class_text, 'basic-info') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <!--ここからコピぺの改造-->
          <%= form_with(model: @user, url: attendances_update_change_one_month_user_path, local: true, method: :patch) do |f| %>
            <% @applicant_change_id_array.each do |applicant_change_id_array| %>
              <% user = User.find(applicant_change_id_array) %>
              <h2>【<%= user.name %>からの勤怠変更申請】</h2>
                <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                  <thead>
                    <tr>
                      <th rowspan = "3">日付</th>
                      <th rowspan = "3">曜日</th>
                      <th colspan= "4">変更前</th>
                      <th colspan= "4">変更後</th>
                      <th rowspan = "3">備考</th>
                      <th rowspan = "3">指示者確認㊞</th>
                      <th rowspan = "3">変更</th>
                      <th rowspan = "3">勤怠を確認する</th>
                    </tr>
                    <tr>
                      <th colspan = "2">出社</th>
                      <th colspan = "2">退社</th>
                      <th colspan = "2">出社</th>
                      <th colspan = "2">退社</th>
                    </tr>
                    <tr>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                    </tr>
                  </thead>
                <tbody>
                  <% attendances = user.attendances.where(mark: 1).where(user_id: user) %>
                  <% attendances.each do |change_attendance| %>
                    <%= f.fields_for "attendances[]", change_attendance do |cf| %>
                      <%
                        css_class = 
                        case $days_of_the_week[change_attendance.worked_on.wday]
                        when '土'
                          'text-primary'
                        when '日'
                          'text-danger'
                        end
                      %>
                      <tr>
                        <td><%= l(change_attendance.worked_on, format: :short) %></td>
                        <td class="<%= css_class %>"><%= $days_of_the_week[change_attendance.worked_on.wday] %></td>
                        <td><%= l(change_attendance.started_at, format: :hour) if change_attendance.started_at.present? %></td>
                        <td><%= format_minute_per_fifteen(change_attendance.started_at) if change_attendance.started_at.present? %></td>
                        <td><%= l(change_attendance.finished_at, format: :hour) if change_attendance.finished_at.present? %></td>
                        <td><%= format_minute_per_fifteen(change_attendance.finished_at) if change_attendance.finished_at.present? %></td>
                        <td><%= l(change_attendance.applying_started_at, format: :hour) if change_attendance.applying_started_at.present? %></td>
                        <td><%= format_minute_per_fifteen(change_attendance.applying_started_at) if change_attendance.started_at.present? %></td>
                        <%= cf.hidden_field :applying_started_at %>
                        <td><%= l(change_attendance.applying_finished_at, format: :hour) if change_attendance.applying_finished_at.present? %></td>
                        <td><%= format_minute_per_fifteen(change_attendance.applying_finished_at) if change_attendance.finished_at.present? %></td>
                        <%= cf.hidden_field :applying_finished_at %>
                        <td><%= change_attendance.applying_note %></td>
                        <%= cf.hidden_field :applying_note %>
                        <td><%= cf.select :mark, [['なし', 0], ['申請中', 1], ['承認', 2], ['否認', 3]], { include_blank: true, selected: change_attendance.mark } %></td>
                        <!--チェックなし　０　チェックあり　１-->
                        <td><%= cf.check_box :change_checked , prompt: "" %></td>  
                        <td><%= link_to "確認する", user_path(change_attendance.user_id, date: change_attendance.worked_on.beginning_of_month), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            <% end %>
 　　　　       <div class="center">
   　　　        <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
            </div>
          <% end %>
         <!--ここまでコピペの改造-->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_apply_overtime.html.erb
<% provide(:class_text, 'basic-info') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <p>ここにテーブルかく</p>



          <!--ここからコピぺの改造-->
          <%= form_with(model: @user, url: attendances_update_apply_overtime_user_path, local: true, method: :patch) do |f| %>
              <h2>【残業申請】</h2>
                <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                  <thead>
                    <tr>
                      <th>日付</th>
                      <th>曜日</th>
                      <th>終了予定時間</th>
                      <th>翌日</th>
                      <th>業務処理内容</th>
                      <th>指示者確認㊞</th>
                    </tr>
                  </thead>
                <tbody>
                      <%
                        css_class = 
                        case $days_of_the_week[@attendance.worked_on.wday]
                        when '土'
                          'text-primary'
                        when '日'
                          'text-danger'
                        end
                      %>
                      <tr>
                        <td><%= l(@attendance.worked_on, format: :short) %></td>
                        <td class="<%= css_class %>"><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
                        <td><%= f.time_field :overtime_finished_at, class: "form-control" %></td>
                        <td><%= f.check_box :tomorrow %></td>
                        <td><%= f.text_field :overtime_note %></td>
                        <td><%= f.collection_select(:overtime_authorizer_id, @overtime_authorizers, :id, :name , prompt: "") %></td>
                            <%= f.hidden_field :id, :value => @attendance.id %>
                            <%= f.hidden_field :user_id, :value => @attendance.user_id %>
                            <%= f.hidden_field :overtime_mark, :value => 1 %>
                      </tr>
                </tbody>
              </table>
              <%= f.submit "変更を送信する", class: "btn btn-block btn-primary" %>
          <% end %>
         <!--ここまでコピペの改造-->





 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_judgment_overtime.html.erb
<% provide(:class_text, 'basic-info') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <!--ここからコピぺの改造-->
          <%= form_with(model: @user, url: attendances_update_judgment_overtime_user_path, local: true, method: :patch) do |f| %>
            <% @judgment_overtime_attendances_id_array.each do |judgment_overtime_attendances_id| %>
              <% user = User.find(judgment_overtime_attendances_id) %>
              <h2>【<%= user.name %>からの勤怠変更申請】</h2>
                <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                  <thead>
                    <tr>
                      <th>日付</th>
                      <th>曜日</th>
                      <th>終了予定時間</th>
                      <th>指定勤務終了時間</th>
                      <th>時間外時間</th>
                      <th>業務処理内容</th>
                      <th>指示者確認㊞</th>
                      <th>変更</th>
                      <th>勤怠を確認する</th>
                    </tr>
                  </thead>
                <tbody>
                  <% attendances = user.attendances.where(overtime_mark: 1).where(user_id: user) %>
                  <% attendances.each do |user_overtime_attendance| %>
                    <%= f.fields_for "attendances[]", user_overtime_attendance do |uf| %>
                      <%
                        css_class = 
                        case $days_of_the_week[user_overtime_attendance.worked_on.wday]
                        when '土'
                          'text-primary'
                        when '日'
                          'text-danger'
                        end
                      %>
                      <tr>
                        <td><%= l(user_overtime_attendance.worked_on, format: :short) %></td>
                        <td class="<%= css_class %>"><%= $days_of_the_week[user_overtime_attendance.worked_on.wday] %></td>
                        <td><%= l(user_overtime_attendance.overtime_applying_finished_at, format: :time) %></td>
                        <td><%= l(user.designated_work_end_time, format: :time) %></td>
                                <!--小数点以下第２位までを表示させる　　　sprintf("%.2f", xxx)-->
                        <!--計算用に日付を申請日に変更する-->
                        <% calc_designated_work_end_time = user.designated_work_end_time.change(month: user_overtime_attendance.worked_on.month, day: user_overtime_attendance.worked_on.day) %>
                        <td><%= sprintf("%.2f", (user_overtime_attendance.overtime_applying_finished_at - calc_designated_work_end_time) / 60 /60) %></td>
                        <td><%= user_overtime_attendance.overtime_applying_note %></td>
                        <td><%= uf.select :overtime_mark, [['なし', 0], ['申請中', 1], ['承認', 2], ['否認', 3]], { include_blank: true, selected: user_overtime_attendance.overtime_mark } %></td>
                        <!--チェックなし　０　チェックあり　１-->
                        <td><%= uf.check_box :overtime_change_checked %></td>
                            <%= uf.hidden_field :view_date, :value =>@view_date %>
                        <td><%= link_to "確認する", user_path(user_overtime_attendance.user_id,date: user_overtime_attendance.worked_on.beginning_of_month), class: "btn btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            <% end %>
 　　　　       <div class="center">
   　　　        <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
            </div>
          <% end %>
         <!--ここまでコピペの改造-->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime.html.erb
<% provide(:class_text, 'basic-info') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <!--ここからコピぺの改造-->
          <%= form_with(model: @user, url: attendances_update_overtime_user_path(@user), local: true, method: :patch) do |f| %>
              <h2>【残業申請】</h2>
                <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                  <thead>
                    <tr>
                      <th>日付</th>
                      <th>曜日</th>
                      <th><span class="label label-danger">必須</span>　終了予定時間</th>
                      <th>翌日</th>
                      <th><span class="label label-danger">必須</span>　終業務処理内容</th>
                      <th><span class="label label-danger">必須</span>　指示者確認㊞</th>
                    </tr>
                  </thead>
                <tbody>
                      <% @overtime_attendances.each do |day| %>
                        <%
                          css_class = 
                          case $days_of_the_week[day.worked_on.wday]
                          when '土'
                            'text-primary'
                          when '日'
                            'text-danger'
                          end
                        %>
                        <%= f.fields_for "attendances[]", day do |af| %>
                        <tr>
                          <td><%= l(day.worked_on, format: :short) %></td>
                          <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
                          <td><%= af.time_field :overtime_applying_finished_at, class: "form-control" %></td>
                          <td><%= f.check_box :tomorrow %></td>
                          <td><%= af.text_field :overtime_applying_note %></td>
                          <td><%= af.collection_select(:overtime_authorizer_id, @overtime_authorizers, :id, :name , prompt: "") %></td>
                          
                              <%= af.hidden_field :user_id, :value => day.user_id %>
                              <%= af.hidden_field :overtime_mark, :value => 1 %>
                        </tr>
                    <% end %>
                      <% end %>
                </tbody>
              </table>
              <%= f.submit "変更を送信する", class: "btn btn-block btn-primary" %>
          <% end %>
         <!--ここまでコピペの改造-->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/change_one_month.js.erb
$("#attendances-change-one-month").html("<%= escape_javascript(render 'attendances/change_one_month') %>");
$("#attendances-change-one-month").modal("show");

app/views/attendances/changed_logs.html.erb
<% provide(:title, "勤怠ログ") %>
<% provide(:class_text, 'user--edit') %>

<div>
  <h1>勤怠ログ</h1>
  <table class="table table-bordered table-condensed user-table">
    <thead>
      <tr>
        <th>日付</th>
        <th>変更前出社時間</th>
        <th>変更前退社時間</th>
        <th>変更後出社</th>
        <th>変更後退社</th>
        <th>指示者</th>
        <th>承認日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>

  </table>
</div>

app/views/attendances/edit_apply_overtime.js.erb
$("#edit-apply-overtime").html("<%= escape_javascript(render 'attendances/edit_apply_overtime') %>");
$("#edit-apply-overtime").modal("show");

app/views/attendances/edit_judgment_overtime.js.erb
$("#edit_judgment_overtime").html("<%= escape_javascript(render 'attendances/edit_judgment_overtime') %>");
$("#edit_judgment_overtime").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>

<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>

  <div>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th><span class="label label-danger">必須</span>　出社</th>
          <th><span class="label label-danger">必須</span>　退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th><span class="label label-danger">必須</span>　指示者確認㊞</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>

        
          <%
            css_class = 
            case $days_of_the_week[day.worked_on.wday]
            when '土'
              'text-primary'
            when '日'
              'text-danger'
            end
          %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
          
        
          <% if day.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger">
                入力エラーが<%= day.errors.count %>件ありました。
              </div>
              <ul>
                <% day.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          
          
          <tr>
            <th><strong><%= l(day.worked_on, format: :short) %></strong></th>
            <th class="<%= css_class %>"><strong><%= $days_of_the_week[day.worked_on.wday] %></strong></th>
            <% if Date.current < day.worked_on %>
              <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
              <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
            <% else %>
              <td>
                <%= attendance.time_field :applying_started_at, class: "form-control" %>
              </td>
              <td><%= attendance.time_field :applying_finished_at, class: "form-control" %></td>
            <% end %>
            <td><%= attendance.check_box :change_tomorrow %></td>
            <td>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= working_times(day.started_at, day.finished_at) %>
              <% end %>
            </td>

            <td><%= attendance.text_field :applying_note, class: "form-control" %></td>
            <td>
              <%= attendance.collection_select(:applying_change_authorizer_id, @change_authorizers, :id, :name , prompt: "") %>
            </td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %> 
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>

  </div>
<% end %>

app/views/attendances/edit_overtime.js.erb
$("#edit-overtime").html("<%= escape_javascript(render 'attendances/edit_overtime') %>");
$("#edit-overtime").modal("show");

app/views/attendances/log_index.html.erb
<% provide(:title, "勤怠ログ") %>
<% provide(:class_text, 'user--edit') %>

<div>
  <h1>勤怠ログ</h1>

  <!--ここから先が検索機能の実装部-->
  <%= form_with url: attendances_log_index_user_path, method: :get, local: true do |f| %>
    <%= f.select :selected_year, [['2019年', 2019],['2020年', 2020]], { include_blank: true}, { class: "form-control width-100" } %>
    <%= f.select :selected_month, [['1月', 1], ['2月', 2], ['3月', 3], ['4月', 4], ['5月', 5], ['6月', 6], ['7月', 7], ['8月', 8], ['9月', 9], ['10月', 10], ['11月', 11],['12月', 12]], { include_blank: true}, { class: "form-control width-100" } %>
    <%= f.submit '検索', { class: "form-control btn-primary mb-20 width-100" } %>
  <% end %>
  <!--ここまで-->
  
  
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>変更前出社時間</th>
        <th>変更前退社時間</th>
        <th>変更後出社時間</th>
        <th>変更後退社時間</th>
        <th>承認者</th>
        <th>承認日</th>
      </tr>
    </thead>
    <tbody>
      <% if @attendances.count > 0 %>
        <% @attendances.each do |attendance| %>
        <tr>
          <td><%= l(attendance.worked_on, format: :short) %></td>
          <td><%= l(attendance.previous_started_at, format: :time) if attendance.previous_started_at.present? %></td>
          <td><%= l(attendance.previous_finished_at, format: :time) if attendance.previous_finished_at.present? %></td>
          <td><%= l(attendance.started_at, format: :time) if attendance.started_at.present? %></td>
          <td><%= l(attendance.finished_at, format: :time) if attendance.finished_at.present? %></td>
          <td><%= User.find(attendance.change_authorizer_id).name %></td>
          <td><%= attendance.approval_date %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>

  </table>
</div>